name: sportshop

services:
  products-microservice:
    container_name: products-microservice
    image: ghcr.io/bkalinovski/sportshop.products:latest
    ports:
      - 8000:8080
    environment:
      - TZ=Europe/Chisinau
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - AllowedHosts=*
      - Logging:LogLevel:Default=Warning
      - Logging:LogLevel:Microsoft.Hosting.Lifetime=Information
      - Logging:LogLevel:SportShop.Products=Information
      - Logging:LogLevel:SportShop.Products.Seeder=Debug
      - ConnectionStrings:ApplicationDatabase=Host=products-db:5432;Database=ProductsDb;Username=sa;Password=A5gK94ez2hgD;
      - S3:Url=http://s3-storage:9000
      - S3:ProxyUrl=http://localhost:9000
      - S3:AccessKey=sportshop
      - S3:SecretKey=dT4C7SI1xMDV
      - S3:Bucket=products
    depends_on:
      - products-db
    entrypoint:
      - bash
      - "-c"
      - |
        dotnet tools/SportShop.Products.Seeder.dll &&
        dotnet SportShop.Products.dll

  products-db:
    container_name: products-db
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      - TZ=Europe/Chisinau
      - POSTGRES_DB=ProductsDb
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=A5gK94ez2hgD

  s3-storage:
    image: quay.io/minio/minio
    container_name: sportshop-storage
    environment:
      - TZ=Europe/Chisinau
      - MINIO_ROOT_USER=sportshop
      - MINIO_ROOT_PASSWORD=dT4C7SI1xMDV
    ports:
      - 9001:9001
      - 9000:9000
    entrypoint:
      - bash
      - -c
      - |
        minio server /data --console-address :9001 &
        sleep 2
        mc alias set sportshop-storage http://localhost:9000 sportshop dT4C7SI1xMDV &&
        mc mb sportshop-storage/products &&
        mc anonymous set public sportshop-storage/products
        wait
